### ISSUE TITLE
GHC mainline testing with Horizon

### ISSUE THREAD

**Issue by locallycompact** [composite-hs/composite-base#8]
Hi. Just to make you aware, composite-base has been added to Horizon Haskell's future proofing repository.

https://gitlab.horizon-haskell.net/package-sets/horizon-advance

This will provide early warning of any breakages due to compiler or library updates.

You'll be pleased to know composite-base is currently building with GHC 9.7 mainline.

You can read more about horizon's package set approach here:

https://horizon-haskell.net

Thank you again for a wonderful library.

**Comment by dfithian** [comment]
Amazing! Let us know if you need a maintainer email to notify for breakages.
